ZoomOut = [["-"],["Keypad -"]]
Clear = [["Escape"]]
RotateCW = [["R"],["."],["Keypad ."]]
InfoPanel = [["I"]]
Flip = [["Space"]]
RotateCCW = [[","],["Keypad 0"]]
Mirror = [["M"]]
Accept = [["Return"]]
PanDown = [["S"],["Keypad 2"]]
TogglePins = [["P"]]
Center = [["X"],["Keypad 5"]]
CloseDialog = [["Escape"]]
PartList = [["K"]]
Quit = [["Q","Ctrl"],["C","Ctrl"]]
Search = [["F","Ctrl"],["/"]]
NetList = [["L"]]
ZoomIn = [["="],["Keypad +"]]
PanRight = [["D"],["Keypad 6"]]
Open = [["O","Ctrl"]]
Validate = [["Return","Shift"]]
PanUp = [["W"],["Keypad 8"]]
PanLeft = [["A"],["Keypad 4"]]

